// src/components/ProjectCard.vue
<template>
  <div class="card">
    <div class="hstack hstack-responsive hstack-space-between align-start">
      <div>
        <h3>{{ project.name }}</h3>
        <p class="text-color-secondary">
          <small>{{ project.timeRange }}</small>
        </p>
      </div>
      <div>
        <div v-if="project.url || project.github">
          <small>
            <div class="grid grid-col-2 grid-gap-m">
              <a v-if="project.url" class="button" v-bind:href="project.url" target="_blank">Website</a>
              <a v-else class="button button-disabled">Website</a>
              <a v-if="project.github" class="button" v-bind:href="project.github" target="_blank">GitHub</a>
              <a v-else class="button button-disabled">GitHub</a>
            </div>
          </small>
        </div>
      </div>
    </div>
    <span v-if="project.imgUrl">
      <a v-bind:href="getProjectImgUrl(project.imgUrl)"><img v-bind:alt="project.imgUrl" class="card card-img margin-s-top margin-s-bottom" v-bind:src="getProjectImgUrl(project.imgUrl)" style="width: 100%; height: 100%;" /></a>
    </span>
    <p>
      {{ project.description }}
    </p>
  </div>
</template>

<script>
export default {
  name: 'ProjectCard',
  props: {
    project: Object
  },
  methods: {
    getProjectImgUrl: function (imgFilename) {
      return require("@/assets/images/projects/" + imgFilename);
    }
  }
}
</script>

// src/components/app/ProjectCard/ProjectCard.tsx
import ReactMarkdown from "react-markdown";
import { Project } from "../../../pages/Projects/@types";
import Button from "../../ui/Button";
import Paper from "../../ui/Paper";

const ProjectCard = ({ project }: { project: Project }) => {
  return (
    <section className="project">
      <Paper>
        <div className="project-header">
          <div className="project-header-info">
            <h3>{project.name}</h3>
            <sub>{project.timeRange}</sub>
          </div>
          <div className="project-header-links">
            <Button url={project.url} newTab={true} disabled={project.url.length === 0}>Website</Button>
            <Button url={project.github} newTab={true} disabled={project.github.length === 0}>Repository</Button>
          </div>
        </div>
        <div className="project-body">
          {
            project.imgUrl ?
              <a href={project.imgUrl} target="_blank" rel="noreferrer">
                <img src={project.imgUrl} width="100%" alt={project.name} loading="lazy" draggable="false" />
              </a>
              :
              <></>
          }
          <ReactMarkdown>
            {project.description}
          </ReactMarkdown>
        </div>
      </Paper>
    </section>
  );
};

export default ProjectCard;
