// src/components/Skills.vue
<template>
  <div class="section width-full">
    <div class="section-header">
      <h3>Skills</h3>
    </div>
    <div class="card card-enter padding-m">
      <div class="hstack margin-l-bottom">
        <input class="width-full" type="text" placeholder="Filter..." @keyup="filter" v-model="filterTerm" />
        <button v-if="this.filterTerm.length > 0" class="margin-s-left cursor-pointer" v-on:click="this.resetResults()">Clear</button>
      </div>
      <span v-if="this.filterTerm.length > 0">
        <h4 class="padding-s-bottom">Results ({{ result.length }} items)</h4>
        <div class="grid grid-gap-m grid-col-1 grid-col-auto-fit-640">
          <div class="grid-item list-freestyle">
            <ul>
              <li v-for="item in this.result" v-bind:key="item">{{ item }}</li>
            </ul>
          </div>
        </div>
      </span>
      <span v-else>
        <h4 class="padding-s-bottom">Programming Languages</h4>
        <div class="grid grid-gap-m grid-col-1 grid-col-auto-fit-640">
          <div class="grid-item list-freestyle card card-inset padding-s">
            <ul>
              <li v-for="item in this.skills['programmingLangs']" v-bind:key="item">{{ item }}</li>
            </ul>
          </div>
        </div>
        <hr />
        <h4 class="padding-s-bottom">Frameworks and Libraries</h4>
        <div class="grid grid-gap-m grid-col-2 grid-col-auto-fit-640">
          <div class="grid-item list-freestyle card card-inset padding-s">
            <h5>Frontend</h5>
            <ul>
              <li v-for="item in this.skills['frameworks']['frontend']" v-bind:key="item">{{ item }}</li>
            </ul>
          </div>
          <div class="grid-item list-freestyle card card-inset padding-s">
            <h5>Backend</h5>
            <ul>
              <li v-for="item in this.skills['frameworks']['backend']" v-bind:key="item">{{ item }}</li>
            </ul>
          </div>
        </div>
        <hr />
        <h4 class="padding-s-bottom">Infrastructure</h4>
        <div class="grid grid-gap-m grid-col-2 grid-col-auto-fit-640">
          <div class="grid-item list-freestyle card card-inset padding-s">
            <h5>Database</h5>
            <ul>
              <li v-for="item in this.skills['infrastructure']['database']" v-bind:key="item">{{ item }}</li>
            </ul>
          </div>
          <div class="grid-item list-freestyle card card-inset padding-s">
            <h5>Cloud</h5>
            <ul>
              <li v-for="item in this.skills['infrastructure']['cloud']" v-bind:key="item">{{ item }}</li>
            </ul>
          </div>
          <div class="grid-item list-freestyle card card-inset padding-s">
            <h5>Continuous Integration</h5>
            <ul>
              <li v-for="item in this.skills['infrastructure']['ci']" v-bind:key="item">{{ item }}</li>
            </ul>
          </div>
          <div class="grid-item list-freestyle card card-inset padding-s bg-color-secondary">
            <h4>Platforms / Operating Systems</h4>
            <ul>
              <li v-for="item in skills['infrastructure']['operatingSystems']" v-bind:key="item">{{ item }}</li>
            </ul>
          </div>
        </div>
      </span>
    </div>
  </div>
</template>

<script>
import skillsJSON from '@/assets/skills.json'

export default {
  name: 'Skills',
  data() {
    return {
      skills: skillsJSON,
      filterTerm: '',
      result: []
    }
  },
  methods: {
    filter: function () {
      this.result = this.skills['programmingLangs'].concat(this.skills['frameworks']['frontend'], this.skills['frameworks']['backend'], this.skills['infrastructure']['database'], this.skills['infrastructure']['cloud'], this.skills['infrastructure']['ci']).filter(item => item.toLowerCase().includes(this.filterTerm.toLowerCase()));
    },
    resetResults: function () {
      this.filterTerm = "";
      this.result = [];
    }
  }
}
</script>

// src/lib/skills/Skills.svelte
<script lang="ts">
  import skillsJson from "./skills.json";
</script>

<section class="card">
  <div class="heading">
    <span class="title">
      <h2>Skills</h2>
    </span>
  </div>
  <div class="body">
    <section class="subsection">
      <h3>Programming Languages</h3>
      <p>{skillsJson.programmingLangs.join(', ')}</p>
    </section>
    <section class="subsection">
      <h3>Frameworks</h3>
      <div class="showcase">
        <section class="subsection">
          <h4>Frontend</h4>
          <p>{skillsJson.frameworks.frontend.join(', ')}</p>
        </section>
        <section class="subsection">
          <h4>Backend</h4>
          <p>{skillsJson.frameworks.backend.join(', ')}</p>
        </section>
      </div>
    </section>
    <section class="subsection">
      <h3>Infrastructure</h3>
      <div class="showcase">
        <section class="subsection">
          <h4>Database</h4>
          <p>{skillsJson.infra.database.join(', ')}</p>
        </section>
        <section class="subsection">
          <h4>Cloud</h4>
          <p>{skillsJson.infra.cloud.join(', ')}</p>
        </section>
      </div>
      <div class="showcase">
        <section class="subsection">
          <h4>CI/CD</h4>
          <p>{skillsJson.infra.cicd.join(', ')}</p>
        </section>
        <section class="subsection">
          <h4>Operating Systems</h4>
          <p>{skillsJson.infra.operatingSystems.join(', ')}</p>
        </section>
      </div>
    </section>
  </div>
</section>

<style>
  section :is(h1, h2, h3, h4) {
    margin: 0 0 0.5rem 0;
  }
  .card .heading .title h2 {
    margin: 0;
  }

  .showcase,
  .showcase :is(:first-child, :last-child) {
    grid-auto-flow: unset;
    grid-template-columns: repeat(2, 1fr);
    gap: 0.5rem;
    justify-content: flex-start;
    align-items: stretch;
    margin: 0;
    padding: 0.25rem;
    width: 100%;
  }

  .subsection {
    margin: 0 0 1rem 0;
  }
  .showcase section.subsection {
    padding: 0.75rem;
  }

  @media (max-width: 767px) {
  .showcase section.subsection {
    padding: 0.125rem 0.5rem;
    border-left: 3px solid var(--accent-color);
  }
  }
</style>
