// src/routes/projects.svelte
<script context="module" lang="ts">
	import { dev } from '$app/env';
	
	export const hydrate = dev;
	export const prerender = true;
</script>

<script lang="ts">
	import { onMount } from "svelte";
	import SvelteMarkdown from "svelte-markdown";
	import SectionedPage from "$lib/ui/SectionedPage.svelte";
	import projectsJson from "$lib/projects/projects.json";

	const noItemsMessage = "Could not retrieve projects. Try reloading the page.";

	onMount(() => {
		document.getElementsByTagName("main")[0].scrollTo({ top: 0 });
	});
</script>

<SectionedPage
	title="Projects"
	description="A selection of personal projects."
	sections={projectsJson.projects}
	noItemsMessage={noItemsMessage}
>
	<svelte:fragment slot="section-list">
		{#each projectsJson.projects as project}
			<section class="card" id={project.id}>
				<div class="heading">
					<span class="title">
						<h2>{project.name}</h2>
						<sub>{project.timeRange}</sub>
					</span>
					<span class="accessories">
						<a class="button" href={project.url ?? undefined} target={project.url ? "_blank" : undefined} class:disabled={!project.url}>Website</a>
						<a class="button" href={project.github ?? undefined} target={project.url ? "_blank" : undefined} class:disabled={!project.github}>Repository</a>
					</span>
				</div>
				<div class="body">
					{#if project.imgUrl.length > 0}
						<img
							loading="lazy"
							decoding="async"
							src={`/img/${project.imgUrl}`} alt={project.name}
							width="100%"
						/>
					{/if}
					<p><SvelteMarkdown source={project.description} /></p>
				</div>
			</section>
		{:else}
			<p>{noItemsMessage}</p>
		{/each}
	</svelte:fragment>
</SectionedPage>

// src/pages/Projects/index.tsx
import { useEffect } from "react";
import "./index.css";
import retitle from "../../lib/retitle";
import { ProjectData } from "./@types";
import rawProjectData from "./projects.json";
import Paper from "../../components/ui/Paper";
import ReactMarkdown from "react-markdown";
import Button from "../../components/ui/Button";

const projectData = rawProjectData as ProjectData;

const Projects = () => {
  useEffect(() => {
    document.title = retitle("Projects");
  }, []);

  return (
    <article id="page-projects" className="top-level-page">
      <h2>Projects</h2>
      <div className="article-body">
        <nav>
          {
            projectData.projects.map((project) => {
              const keyName = `project-shortcut-${project.id}`;
              return (
                <a key={keyName} href={`#${keyName}`}>
                  {project.name}
                </a>
              );
            })
          }
        </nav>
        <div className="article-content projects">
          {
            projectData.projects.map((project) => {
              return (
                <section id={`project-shortcut-${project.id}`} key={`project-item-${project.id}`}>
                  <Paper>
                    <div className="project-header">
                      <h3>{project.name}</h3>
                      <div className="project-header-links">
                        <Button url={project.url} newTab={true} disabled={project.url.length === 0}>Website</Button>
                        <Button url={project.github} newTab={true} disabled={project.github.length === 0}>Repository</Button>
                      </div>
                    </div>
                    {
                      project.imgUrl ?
                        <img src={project.imgUrl} width="100%" />
                        :
                        <></>
                    }
                    <ReactMarkdown>
                      {project.description}
                    </ReactMarkdown>
                  </Paper>
                </section>
              );
            })
          }
        </div>
      </div>
    </article>
  );
};

export default Projects;
